/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const COUPLE_DATA = {
  name: "rizkyyy & mitaaa 🤍",
  nickname: "sayanggg",
  startDate: "2025-08-16T22:25:00Z",
  anniversaryDate: "2026-08-16T22:25:00Z"
};

export const ASSETS = {
  photos: [
    "/images/foto1.jpg",
    "/images/foto2.jpg",
    "/images/foto3.jpg",
    "/images/foto4.jpg",
    "/images/foto5.jpg"
  ],

  video: "https://www.image2url.com/r2/default/videos/1778839319324-fd48ec62-bd0e-472e-a2c7-48f03595c7e0.mp4",

  audioMain: "https://www.image2url.com/r2/default/audio/1778824352930-3001d071-3d76-4e36-89c7-619baccba4c1.mp3",

  audioVoice: "https://www.image2url.com/r2/default/audio/1778823994135-083c391a-c6a2-4041-82de-667c3410ad2c.mp3"
};

export const LOVE_LETTER = "SAYAAAANGGGGGG AKHIRNYAAA KITAA SAMPAIII DIIIII 9 BULANNN KITAAA, GAAA TERASAAA SEBENTARR LAGII KITAAAA UDAAAHH 1 TAHUNN HAHAHAHH, RASANYAAA KAYAAA GAAA NYANGKAAA GITUUU KANNN SAYANGG, KITAAA PUTUSSS BUKANNN SEKALII DUAAA KALII, TAPIII KITAA MASIHH KEMBALIII KEEE RUMAHHH MASINKK MASINKK YAITUU HUBUNGANNYAA KITAAA, KARENAA DII ORANGG BARUU GABAKALAN ADAA HALL YANGG SAMAAA PASTII AKANN BEDAA RASANYAA WALAUPUNN CARANYAAA SAMAAA, MAAAFINNN RIZKYY KALAUU BELUMMM BISAAA JADIII COWOOO YANGGG BENERR BENERRR BAIKK BUATT KAMUU, KADANGG RIZKYY MASIHH SUKAAAAA NGAMBEKKK EGOISSS DANNN BANYAKKK LAGIIII, TAPII PERLAHAN LAHANN SEMOGAA RIZKYYY BISAAAAAA HILANGINNNN SIFATT ITUU YAAA SAYANGG, RIZKYY GAAA NYANGKAAAA KITAAA SEJAUHH INIII SAMPAIII KEE TITIKK INIKKK PADAHALLL PERTAMAA KALINAAA KITAAA GADAAA PDKTAN SAMAAA SEKALIIII WOIKK HAHAHHAHA, CUMAN DARI KAMUU YANGG MINTA SAVE KE RIZKY RIZKY SAVE KAMU KODE RIZKYNYA NEMBAK KAMUU HAHAHAHAA SENENK BANETT PLCCC KAYAAA KO BISAA YAAA GAA NYANGKAA BANGETTT, KALAUU NANTII KITAA BENERANNN NIKAHH DANN UDAAA PUNYAAAA ANAAAKKK, ANAKK KITAA NANYAAA MISALL MANGGGILL DADDY AND MOMMY HAHAHAHAH DITANYAA DIAKKK DADD MOMM KALIANN BERDUAA AWALAAN JADIANNYAA GIMANAAA OMAYGATT KITAA BAKALANN CERITAINN KISAHH KITAKKK YANKK KAYAA GAA MUNGKINN TAPIKK TERJADIKK INIKK SAYANKK HAHAAHA, NANTII RIZKYY BILANLNYAAAA DULUU DADDY SUKAA MOMMY DARI DADDDY KELAS 8 HAHAHAHAHAHHAA 
MOMMY BARU NGESUKAIN DADDY BALIK PAS UDAH KELAS 9 BWEHH BAYANGINN SAYANKK SEEE SERUU DANN SEE EXCITED APAAA NANTINAAA KITAA CERITAINN KEE ANAKK KITAKKK HAHAHAHAHAH, KAYAAA RASANYAA KOO BISAA YAA PADAHALL DULUU RIZKY UDAHH PUTUS ASAA GABISAA JADIAN BARENK KAMUU PLCCC, RIZKYYY ITUU SETIAPP CLASSMEET SELALUU DIBELAKANGGG KAMUU🥺, PWIS DEH KAMUWNYAAA GAMAUWKKK NGELIATT KAYAA SOMBONKNAAAA HAHAHAHA, TAPIWKK ISOKEII SAYANKK SEKARANK KITAKK SUDAA JADIANN BIARR KISAH KITAA ITUWKK ADAA GREGETNAA ADAAA OMAYGAT AND AW AWNAAAA HAHAHAHA, RIZKYY SAYAAAANKK BANETYT SAAMAAA KAMUWKK, SETIAPP HARINAAA CINTAA RIZKY GAPERNAHH BERKURANKK BUATT KAMUU SAYANKK, CINTAA RIZKYY PASTINAAA SETIAPP HARII SETIAPP DETIK BAKALANN BERTAMBAHH, RIZKYY BENERANNN BARUU PERTAMAAA KALII NGERASAINN PUNYAAA HUBUNGANN YANGG BAII RASANAA BEGINIKKK, KAYAAA DARII CARAA KAMUU NGECINTAII RIZKYY, NGESAYANGIII RIZKYYY, MENUHINNN KEMAUANNYA RIZKYY, DANN BANYAAK LAGII LAINNYAAA, MAKANYAAA RIZKYY KALAUU DII DEKETT KAMUU ITUU SELALUU KAYAAAAA BENERR BENERRR SUKAA BANGETT KAMU KAYAA RUMAH NYAMANN BAGIKK RIZKYY, SETIAPP MEGANKK TANGAN KAMUU DAN ADA DI DEKET KAMU RASANYA RIZKY BENER BENER GAMAUU LEPAS DANNN GAMAUU KEMANA MANAA RIZKYY SAYANGG BANGET SAMA KAMUU, KALAU DI DEKET KAMU RIZKY SELALUU NGERASAA AMANNN TENANKKKK BANGETYT PLCCC, APALAGI KALAUU UDAA MANDANKK MUKAAA KAMUU RIZKYY BISAAA NGERASAINN ADEMMMM SEJUKKKKKKK BANETTT, KARENAA KAMUU ITUU CANTINYAA GAAA CANTII BIASAAA SAYANGG, KAMUU CANTINYAA BEDAA DARII YANGG LAINNN KAMU BENERANNN SEMPURNA 100% DIMATAKK RIZKYY KAMU CANTII, PINTERR, BAIII,LUCUU,IMUTT BANYAAA LAGIWKK YANKK GABISAA RIZKYY SEBUTINN HAHAHAHAHA, APALAGIWK KAMOE HOT DAN AW AW HAHAHAHAHHAAHAHA KIW KIWW, RIZKYY GATAUWKK MAUWW NGETIKK APAKK LAGIWKK, RIZKY ITUWKK BANYAKK DAPETINN FIRST EXPERIENCE DII KAMUWKK, TERIMAA KASIHH UDAAAH MAUWWW SELALUUUU NEMENINNN KELUHH KESAH BARENKK RIZKYYY YAAA SAYANKK, KAMUU TETEPP BERTAHANN SAMAA RIZKYY WALAUPUNN ADAA SEDIHNYAA, KAMUU TETEPP GAA NGEDUAIN RIZKY WALAUPUN BANYAAA COWOO LAINNAA YANK LEBIHHH BAIKK DARII RIZKY YANG JAUH LEBIHH DARI RIZKY TAPII KAMUUU TETEPP BARENKK RIZKYY RIZKY IS VERY LUCKYY TOO BEEE LOVEDDD BYY UUU, PWISSS LOWAV BANETT XIXIXIXI, JANGANNNN TINGGAAAALINN RIZKYYY YAAAA SAYANGGG RIZKYYY BERUNTUNK BANET UDAHH DAPETIN WANITAA SESEMPURNA KAMUU AIYW LOAVV YUWW MOREE ANDD ANIYTINKK SAYANKK🤍🤍🤍
SEMOGAA HUBUNGAN KITAA BENERANNN BISA NGECAPAI DI TITIK BAHAGIA DAN DI TITIK GABAKALAN PISAH SELAMANAA YAA SAYANKK🤍🤍🤍";
